- name: Demo on conditions
  hosts: localhost
  vars:
    abc: ABC
    val: 100
  tasks:
    - name: Condition with String
      debug:
        msg: "abc var = ABC"
      when: abc == "ABC"
    - name: Condition with String
      debug:
        msg: "abc var = abc"
      when: abc == "abc"

    - name: Condition with Number
      debug:
        msg: "Val var is less than 100"
      when: val < 100

    - name: Condition with Number
      debug:
        msg: "Val var is greater than or equal to 100"
      when: val >= 100
