- name: Play1
  hosts: all
  strategy: free
  tasks:
    - name: Sleep for 10 s
      shell: sleep 5
    - name: Sleep for another 10 s
      shell: sleep 5

#- name: Play2
#  hosts: all
#  #strategy: free
#  tasks:
#    - name: Sleep for 10 s
#      shell: sleep 10
